# Generated by Django 3.0.5 on 2020-05-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_districtblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtblock',
            name='state',
        ),
        migrations.AlterField(
            model_name='districtblock',
            name='district_id',
            field=models.IntegerField(),
        ),
    ]
